### PR TITLE
Transform all instances of camel-cased `Url` to Uppercased `URL`

### LINKED ISSUE #134: Agree on and implement URL naming
Let's agree on how to use the `URL` word in names of types and fields.

From what I've seen, this works:

Always uppercased, **except** when it's **at the beginning** of a field, variable, method name, or if **it's the word `url` alone**.
My question is at the middle of the name. I've usually tended to make them lowercased, but as a general rule, it's simpler if we make it also uppercased (one less exception).

### Some examples:

**Types: Always uppercased:**

- `URLSomething`, `SomeURLThing` , `SomethingURL`

**Fields, methods, methd labels, and local variables:**

- Prefixing with `url` lowercased:
  - `let urlSomething` 
  - `func urlThing() -> URL`
- Postfixing with `URL` Uppercased:
  - `let someURL`
  - `func somethingURL()`
- `url` alone lowercased:
  - `let url`
- `URL` in the middle uppercased:
  - `let someURLThing`
  - `func avatarURLThing() -> AvatarURL`

### PR DESCRIPTION
**Pull request by etoledom**
Closes #134 

### Description

Renaming all instances of CamelCased `Url`s to Uppercased `URL`.

### Testing Steps

- 🍏 CI

### CODE REVIEW

File: Sources/Gravatar/Network/UserProfile.swift [hunk 1]
```diff
@@ -18,8 +18,22 @@ public struct UserProfile: Decodable {
...
 
-    public let profileUrl: String
-    public let thumbnailUrl: String
+    private let profileUrl: String
+    public var profileURLString: String {
+        profileUrl
+    }
+    public var profileURL: URL? {
+        URL(string: profileURLString)
+    }
```
Comment (etoledom) [inline Sources/Gravatar/Network/UserProfile.swift]: Kept `profileUrl` as private to be decoded to avoid decoding manually all fields because of these two exceptions.

Also:
Changed to `profileURLString` and added `profileURL: URL?` to be the same as in the `Account` struct

**Review by pinarol — APPROVED** [review]
LGTM but we need tiny changes on the WP side as well.

**Comment by etoledom** [comment]
> LGTM but we need tiny changes on the WP side as well.

@pinarol 

I have created:
- https://github.com/wordpress-mobile/WordPress-iOS/pull/22911
- https://github.com/wordpress-mobile/WordPressUI-iOS/pull/155

And I've also added a coding style document plus 2 links to it (from contributing and from readme)

File: CODINGSTYLE.md [hunk 2]
```diff
@@ -0,0 +1,36 @@
...
+
+### Tooling
+
+We use [SwiftFormat](https://github.com/apple/swift-format) to enforce a basic swift format style.
+
+CI will fail if it finds any format issue.
+
+You can run `SwiftFormat` locally with `make lint` to get warnings, or `make swiftformat` to implement the changes automatically.
+
+### URL, ID, API and other initialisms
```
Comment (pinarol) [inline CODINGSTYLE.md]: I am not a native speaker but this feels better to me. I would appreciate if @andrewdmontgomery also checks.

```suggestion
### URL, ID, API and other acronyms
```

File: CONTRIBUTING.md [hunk 3]
```diff
@@ -6,6 +6,8 @@ The following is a set of guidelines for the many ways you can join our collecti
 
 Before anything else, please take a moment to read our [Code of Conduct](CODE-OF-CONDUCT.md). We expect all participants, from full-timers to occasional tinkerers, to uphold it.
 
+Check out our [Coding Style guide](CODINGSTYLE.md)
```
Comment (pinarol) [inline CONTRIBUTING.md]: Just putting a period at the end.

```suggestion
Check out our [Coding Style guide](CODINGSTYLE.md).
```

File: README.md [hunk 4]
```diff
@@ -24,6 +24,8 @@ Gravatar
 
 ## Coding Style
 
+Check out our [Coding Style guide](CODINGSTYLE.md)
```
Comment (andrewdmontgomery) [inline README.md]: Just putting a period at the end.
```suggestion
Check out our [Coding Style guide](CODINGSTYLE.md).
```

Comment (pinarol) [inline README.md]:
```suggestion
Check out our [Coding Style guide](CODINGSTYLE.md).
```

**Review by pinarol — APPROVED** [review]
I don't need to check again, feel free to merge after the updates we discussed.

**Review by andrewdmontgomery — APPROVED** [review]
Yeah, looks good to me, too.
