### PR TITLE
Fix warnings

### LINKED ISSUE #268: [Concurrency] Improve demo app concurrency
Let's turn on strict concurrency checking in the demo app and resolve all warnings & errors.

### PR DESCRIPTION
**Pull request by pinarol**
Closes #268

### Description

Fix warnings related to deprecations and concurrency.

### Testing Steps

CI green

Demo app:
Profile View Controller > Customize avatar

### CODE REVIEW

File: Demo/Demo/Gravatar-Demo/SwiftUI/DemoAvatarView.swift [hunk 1]
```diff
@@ -44,7 +44,11 @@ struct DemoAvatarView: View {
                 Divider()
                 AvatarView(
                     url: avatarURL?.url,
-                    placeholder: Image("profileAvatar").renderingMode(.template),
```
Comment (pinarol) [inline Demo/Demo/Gravatar-Demo/SwiftUI/DemoAvatarView.swift:47]: fixes deprecated warning.

File: Demo/Demo/Gravatar-Demo/DemoProfilePresentationStylesViewController.swift [hunk 2]
```diff
@@ -78,19 +78,23 @@ class DemoProfilePresentationStylesViewController: DemoBaseProfileViewController
...
         case .standard:
-            config = ProfileViewConfiguration.standard(palette: preferredPaletteType)
+            config = ProfileViewConfiguration.standard(palette: paletteType)
         case .summary:
-            config = ProfileViewConfiguration.summary(palette: preferredPaletteType)
+            config = ProfileViewConfiguration.summary(palette: paletteType)
         }
         config.avatarIdentifier = profileIdentifier?.avatarIdentifier
         if customizeAvatarSwitchWithLabel.isOn {
-            config.avatarConfiguration.borderColor = .green
```
Comment (pinarol) [inline Demo/Demo/Gravatar-Demo/DemoProfilePresentationStylesViewController.swift:93]: fixes deprecated warning.

File: Demo/Demo/Gravatar-Demo/SwiftUI/TestImageCropper.swift [hunk 3]
```diff
@@ -5,7 +5,7 @@ struct TestImageCropper: View, ImageEditorView {
     var inputImage: UIImage
     var editingDidFinish: (@Sendable (UIImage) -> Void)
     
-    init(inputImage: UIImage, editingDidFinish: @escaping (UIImage) -> Void) {
```
Comment (pinarol) [inline Demo/Demo/Gravatar-Demo/SwiftUI/TestImageCropper.swift:8]: fixes concurrency warning.

File: Tests/GravatarUITests/OAuthSessionTests.swift [hunk 4]
```diff
@@ -140,7 +140,7 @@ private class AuthenticationSessionMock: AuthenticationSession, @unchecked Senda
     }
 }
 
-final class TestStorage: SecureStorage {
```
Comment (pinarol) [inline Tests/GravatarUITests/OAuthSessionTests.swift:143]: fixes concurrency warning.

File: Demo/Demo/Gravatar-Demo/DemoImageCropperViewController.swift [hunk 5]
```diff
@@ -76,7 +76,7 @@ extension DemoImageCropperViewController: PHPickerViewControllerDelegate {
         if result.itemProvider.canLoadObject(ofClass: UIImage.self) {
             result.itemProvider.loadObject(ofClass: UIImage.self) { [weak self] (object, error) in
                 if let image = object as? UIImage {
-                    DispatchQueue.main.async {
```
Comment (pinarol) [inline Demo/Demo/Gravatar-Demo/DemoImageCropperViewController.swift:79]: fixes concurrency warning.

**Review by etoledom — APPROVED** [review]
Looks good!
