### PR TITLE
Fix truncated text content in the QuickEditor

### LINKED ISSUE #726: Error text is truncated in the Quick Editor
Error text is truncated in the Quick Editor:

Image

### PR DESCRIPTION
**Pull request by pinarol**
Closes #726

### Description

The problem is that for some reason the text is shrunk vertically. So I am making use of [fixedSize(horizontal:vertical:)](https://developer.apple.com/documentation/swiftui/view/fixedsize(horizontal:vertical:)) to vertically fix the content this way it won't shrink.

### Testing Steps

Go to QuickEditor
Login with email A
Use the logout button in the demo app
Change the email in the demo app
Start QuickEditor but use email A for the OAuth flow
This will generate the wrong email error
Observe that the error text is not truncated

Additonal:

Test the intro state
Test in landscape orientation

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">You need to add at least one label to this PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: Sources/GravatarUI/SwiftUI/ProfileEditor/QuickEditorNoticeView.swift [hunk 1]
```diff
@@ -59,6 +59,7 @@ struct QuickEditorNoticeView: View {
             )
             .padding(.bottom, .DS.Padding.double)
         }
+        .fixedSize(horizontal: false, vertical: true)
```
Comment (pinarol) [inline Sources/GravatarUI/SwiftUI/ProfileEditor/QuickEditorNoticeView.swift:62]: This second one is not specifically required to fix this bug but I added it to cover all the other content just in case.

**Review by etoledom — APPROVED** [review]
Looking great!

Tested also using accessibility text sizes, double length pseudo language, landscape mode, and the intro screen (forcing multiple lines).
